<a href="https://colab.research.google.com/github/LEESUNG02/colab_note/blob/main/230620_%EA%B8%B0%EC%88%A0%ED%86%B5%EA%B3%84%2B%EB%82%9C%EC%88%98%EB%B0%9C%EC%83%9D%EA%B3%BC%2B%EC%B9%B4%EC%9A%B4%ED%8C%85_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 기술 통계

## 기술 통계(descriptive statistics)
> 데이터 집합에 대해 통계를 계산
* 데이터의 개수(count)
* 평균(mean, average)
* 분산(variance)
* 표준 편차(standard deviation)
* 최댓값(maximum)
* 최솟값(minimum)
* 중앙값(median)
* 사분위수(quartile)

In [ ]:
import numpy as np

In [ ]:
x = np.array([
    18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8,
    2, 5, 4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13
])
x

array([ 18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
         2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

## 데이터의 개수

In [ ]:
len(x)

26

## 표본 평균
* 우리가 일반적으로 아는 평균
* 통계용어로는 표본 평균(sample average, sample mean)
<br>
$
\bar{x} = \frac{1}{N}\displaystyle\sum_{i=1}^{N}{x_i}
$
(𝑁은 데이터의 개수)

In [ ]:
np.mean(x), x.mean()

(4.8076923076923075, 4.8076923076923075)

## 표본 분산
* 표본 분산(sample variance) : 데이터와 표본 평균간의 거리의 제곱의 평균
* 표본 분산이 작으면 데이터가 모여있는 것이고 크면 흩어져 있는 것
<br>
$
s^2 = \frac{1}{N}\displaystyle\sum_{i=1}^{N}{(x_i-\bar{x})^2}
$

In [ ]:
np.var(x), x.var()

(115.23224852071006, 115.23224852071006)

## 표본 표준편차
* 표본 표준편차(sample standard variance) : 표본 분산의 양의 제곱근 값
<br>
$
s = \sqrt{s^2}
$

In [ ]:
np.std(x), x.std()

(10.734628476137871, 10.734628476137871)

## 최댓값과 최솟값

In [ ]:
# 최댓값 (maximum) / 최솟값 (minimum)
np.max(x), x.max(), np.min(x), x.min()

(23, 23, -24, -24)

## 중앙값
* 중앙값(median) : 데이터를 크기대로 정렬하였을 때 가장 가운데에 있는 수
* 만약 데이터의 수가 짝수이면 가장 가운데에 있는 두 수의 평균을 사용


In [ ]:
np.median(x) # 내장 메소드 x

5.0

## 사분위수
* 사분위수(quartile) : 데이터를 가장 작은 수부터 가장 큰 수까지 크기가 커지는 순서대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수
* 각각 1사분위수, 2사분위수, 3사분위수라고 함
* 1/4의 위치란 전체 데이터의 수가 만약 100개이면 25번째 순서, 즉 하위 25%
* 따라서 2사분위수는 중앙값과 같음
* 때로는 위치를 1/100 단위로 나눈 백분위수(percentile)을 사용하기도 함
* 1사분위수는 25% 백분위수와 같음


In [ ]:
np.percentile(x, 0) # 최솟값 min

-24.0

In [ ]:
np.percentile(x, 25)  # 25% 백분위수, 1사분위수

0.0

In [ ]:
np.percentile(x, 50)  # 50% 백분위수, 2사분위수, 중앙값

5.0

In [ ]:
np.percentile(x, 75)  # 75% 백분위수, 3사분위수

10.0

In [ ]:
np.percentile(x, 100)  # 100% 백분위수, 4사분위수, 최댓값

23.0

# 난수 발생과 카운팅

## 시드 설정
* 컴퓨터 프로그램에서 발생하는 무작위 수는 사실 엄격한 의미의 무작위 수가 아님
* 어떤 특정한 시작 숫자를 정해 주면 컴퓨터가 정해진 알고리즘에 의해 마치 난수처럼 보이는 수열을 생성. 이런 시작 숫자를 시드(seed)라고 함
* 일단 생성된 난수는 다음번 난수 생성을 위한 시드값이 됨. 따라서 시드값은 한 번만 정해주면 됨.
* 시드는 보통 현재 시각 등을 이용하여 자동으로 정해지지만 사람이 수동으로 설정할 수도 있음 * 특정한 시드값이 사용되면 그 다음에 만들어지는 난수들은 모두 예측할 수 있음
* 고정된 결과를 얻기 위해서 실습엔 시드를 설정

In [ ]:
np.random.seed(0) # 시드값 고정

### `rand` : 0과 1 사이의 난수를 발생

In [ ]:
np.random.rand(5)  # rand(n) : n개의 길이를 가지는 배열에 각각 0~1 사이의 난수를 채워줌

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [ ]:
np.random.rand(10)

array([0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215])

## 데이터의 순서 변경

### `shuffle`
* 데이터의 순서를 변경
* 자체 변환(in-place) 함수 (원본에 영향)

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(x) # x를 섞어줌 -> 자체를 섞어버림
x

array([4, 1, 5, 8, 9, 2, 0, 3, 6, 7])

## 데이터 샘플링
* 표본선택 혹은 샘플링(sampling) : 이미 있는 데이터 집합에서 일부를 무작위로 선택하는 것

### `choice` : 샘플링에 사용
```
numpy.random.choice(a, size=None, replace=True, p=None)
```
* a : 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성
* size : 정수. 샘플 숫자
* replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능 (복원/비복원 추출)
* p : 배열. 각 데이터가 선택될 수 있는 확률

In [ ]:
np.random.choice(5, 5, replace=False) # 5개 중에 5개를 선택 -> 비복원 -> shuffle

array([2, 1, 3, 4, 0])

In [ ]:
np.random.choice(5, 3, replace=False) # 5개 중에 3개를 선택 -> 비복원 -> shuffle

array([4, 2, 3])

In [ ]:
#np.random.choices(5, 10) # 복원 5개 중에 10개를 선택(뽑았던 것을 또 뽑는다)
np.random.choice(5, 10, replace=True)

array([0, 1, 1, 3, 0, 0, 1, 2, 4, 2])

In [ ]:
# [0, 1, 2, 3, 4]
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]) # 복원, 5개 중에 10개를 선택 (뽑았던 것을 또 뽑는다)

array([3, 3, 3, 0, 3, 0, 3, 3, 2, 3])

## 난수 생성
* `rand` : 0부터 1 사이의 균일 분포
* `randn` : 표준 정규 분포
* `randint` : 균일 분포의 정수 난수

### `rand` : 0부터 1 사이에서 균일한 확률 분포로 실수 난수를 생성
* 숫자 인수는 생성할 난수의 크기
* 여러 개의 인수를 넣으면 해당 크기를 가진 행렬을 생성

In [ ]:
np.random.rand(10)

array([0.68866118, 0.88047589, 0.91823547, 0.21682214, 0.56518887,
       0.86510256, 0.50896896, 0.91672295, 0.92115761, 0.08311249])

In [ ]:
np.random.rand(3,5)

array([[0.58846509, 0.65966841, 0.53320625, 0.23053302, 0.39486929],
       [0.61880856, 0.47486752, 0.47013219, 0.71607453, 0.287991  ],
       [0.38346223, 0.74916984, 0.87845219, 0.10286336, 0.09237389]])

### `randn` : 기댓값이 0이고 표준편차가 1인 표준 정규 분포(standard normal distribution)를 따르는 난수를 생성

In [ ]:
np.random.randn(10)

array([-4.06536527e-01,  1.06095115e+00, -1.03522496e-01,  1.41816829e-01,
        5.81819743e-01,  1.35454064e+00,  4.61577057e-01, -6.51715276e-01,
        3.81171943e-05,  8.89754310e-01])

In [ ]:
np.random.randn(3, 5)

array([[-1.27348939,  0.03178615,  0.46235833,  0.35354835, -1.06197932],
       [-0.26135467, -1.17139852, -1.85708744, -0.14481625, -0.48386811],
       [-0.77979698,  1.21390595, -2.12251201, -0.13776681, -0.41732262]])

### `randint`
```
numpy.random.randint(low, high=None, size=None)
```
만약 `high`를 입력하지 않으면 0과 `low`사이의 숫자, `high`를 입력하면 `low`와 `high`는 사이의 숫자를 출력. `size`는 난수의 숫자

In [ ]:
np.random.randint(10, size=10)  # 시작점

array([2, 8, 4, 3, 0, 4, 3, 6, 9, 8])

In [ ]:
np.random.randint(10, 20, size=10)  # 시작점, 끝점

array([10, 18, 15, 19, 10, 19, 16, 15, 13, 11])

In [ ]:
np.random.randint(10, 20, size=(3,5))

array([[18, 10, 14, 19, 16],
       [15, 17, 18, 18, 19],
       [12, 18, 16, 16, 19]])

## 💡 연습문제 7
1. 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 작성하라
2. 주사위를 100번 던져서 나오는 숫자의 평균
3. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하라

In [61]:
# 1.
np.random.choice([0, 1], size=10, replace=True)

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 0])

In [62]:
np.random.choice([0, 1], size=10, replace=True)

array([1, 1, 0, 0, 0, 0, 1, 0, 0, 0])

In [65]:
# 2.
# np.random.randint(1, 7, 100)
# np.random.randint(1, 7, 100), mean()
np.random.choice(range(1, 7), size=100, replace=True).mean()

3.31

In [75]:
# 3.
np.random.randn(250)  # 정규분포!
# 평균(기댓값)이 0이고, 표준편차가 1인 정규분포. 1% -> 0.01

array([-1.25243153,  0.58083555,  0.06593382, -0.05469835,  0.08980445,
       -0.35990857, -1.15538383, -1.94679996, -0.52064647, -1.77169783,
       -0.68963604, -0.57156609,  0.03134201, -1.11431378,  0.29203201,
        0.03551557,  0.11619986,  0.89909405, -0.78440609,  0.26701859,
       -0.67177599, -2.08850056,  1.69717522,  2.75703969,  2.33440988,
       -0.30163745, -2.2370097 ,  1.86559944, -0.38629529, -2.31794572,
        0.1113988 ,  0.58158611, -1.30735878,  0.84745595, -1.14701312,
        0.67291893,  1.18000193,  1.58708418, -0.77239565, -0.96873834,
       -1.06389001, -1.43123383, -1.86660095, -2.13146385,  0.95566836,
        0.36782454,  0.98357763, -0.22950136,  0.7103582 ,  0.42644556,
        1.46503946,  0.64143206,  1.18012521,  0.54718364, -0.04156063,
        0.26973224,  0.22945564,  0.71892616, -1.35437525,  2.22779305,
       -0.86489695,  1.44518385,  0.43159422,  2.05935557,  1.77112996,
       -1.37609029,  0.44849241,  2.232889  , -0.60404464, -0.84

In [76]:
a = np.random.randn(250) / 100  # 일간 수익률이 표준정규분포를 따르는 (0과 0.01 표준편차)
a

array([ 8.00506799e-03,  6.82175340e-03, -6.38075232e-03, -1.30200656e-02,
        6.30262843e-03, -1.61214138e-02,  9.84341411e-04, -9.60708294e-03,
        1.07508306e-02,  9.54179037e-03, -7.80118471e-05, -5.02471610e-03,
        3.73564885e-03,  5.01590193e-03, -3.43325170e-04, -1.00362314e-02,
       -4.33249572e-03,  2.16369380e-03, -1.35345049e-02, -1.34654015e-02,
       -5.22914945e-03,  9.12994551e-03, -6.27658953e-03, -1.88217055e-03,
        1.17977575e-03, -3.73624774e-03,  3.77132004e-03, -1.55555375e-03,
       -1.69529682e-03,  7.68110207e-05, -1.14158531e-03, -9.83278736e-03,
       -3.61133639e-03,  1.85565268e-04,  1.10330373e-02,  4.57796467e-03,
       -2.11673860e-02, -4.65317600e-03,  4.37243874e-03,  2.43483551e-03,
        1.04203233e-02,  1.35146445e-02,  1.76342238e-02, -6.22374884e-03,
       -5.50159160e-03, -2.19540892e-02, -3.46107993e-03,  4.67486848e-03,
       -1.49079178e-02,  1.80285154e-03,  1.12860016e-02,  2.69201846e-03,
        5.04793928e-03, -

In [73]:
start = 10000  # 가격이 10000원 -> 250일 -> 평균/표준편차가 반영되면서 250일.
price = np.empty(250)  # 자리
for i, v in enumerate(a): # a -> 가격이 0의 기댓값, 1%의 표준편차를 바탕으로 250일치의 변화율이 생성
    start *= (1 + v)  # i = index, v = 변화율
    # -> 해당 금액의 변화율이 반영된 금액
    price[i] = start  # 변화율에 따라서 변경된 금액에 배열에 저장.
    # 한 번씩 for이 돌때마다 -> index += 1 => 계속 변화율이 반영된 금액들이 다음 인덱스에 저장

In [74]:
price

array([10002.04824707,  9894.91863231,  9863.58954987,  9757.55534732,
        9669.17882335,  9684.82955139,  9834.88795889,  9782.82496616,
        9923.85344624,  9939.69569381,  9907.08687415,  9793.6404854 ,
        9816.10576592,  9961.22137616, 10080.43461418, 10074.10068034,
       10140.96878166, 10231.98186642, 10234.78896278, 10150.33855226,
       10060.58827906, 10041.83285926, 10105.458296  , 10035.76262468,
       10153.15381196, 10082.52740693,  9979.1220635 ,  9826.40310349,
        9830.16818927,  9798.31234161,  9815.49312111, 10024.25907495,
       10172.5453541 , 10147.72286129, 10137.70305862, 10062.91486019,
       10065.01001957, 10016.76869537,  9988.46049158,  9899.11688132,
        9836.8653124 ,  9770.61752685,  9867.0943155 ,  9890.74403074,
        9898.04260768,  9966.56971985, 10045.70977376,  9884.4157225 ,
       10015.74357925,  9901.00571282,  9929.0174354 ,  9918.75169291,
        9874.55215109,  9854.78073718,  9835.12775164,  9705.67375546,
      

## 정수 데이터 카운팅
* 만약 난수가 정수값이면 unique 명령이나 bincount 명령으로 데이터 값을 분석

### `unique`
* unique 함수는 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력
* return_counts 인수를 True 로 설정하면 각 값을 가진 데이터 갯수도 출력


In [77]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [79]:
a = np.array(list('abca'))
a

array(['a', 'b', 'c', 'a'], dtype='<U1')

In [81]:
np.unique(a, return_counts=True)

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 1, 1]))

In [83]:
index, value = np.unique(a, return_counts=True)
index, value

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 1, 1]))

In [86]:
# dict(np.unique(a, return_counts=True))

In [87]:
index, value

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 1, 1]))

In [88]:
list(zip(index, value))  # 같은 인덱스에 있는 값끼리 튜플화시켜서 묶어줌
# index, value == *np.unique(a, return_counts=True)

[('a', 2), ('b', 1), ('c', 1)]

In [89]:
dict(zip(*np.unique(a, return_counts=True)))  # key, value

{'a': 2, 'b': 1, 'c': 1}

### `bincount`
* `unique` 함수는 데이터에 존재하는 값에 대해서만 갯수를 세므로 데이터 값이 나올 수 있음에도 불구하고 데이터가 하나도 없는 경우에는 정보를 주지 않음
* 따라서 데이터가 주사위를 던졌을 때 나오는 수처럼 특정 범위안의 수인 경우에는 `bincount` 함수에 `minlength` 인수를 설정하여 쓰는 것이 더 편리
* `bincount` 함수는 0 부터 `minlength` - 1 까지의 숫자에 대해 각각 카운트
* 데이터가 없을 경우에는 카운트 값이 0이 됨

In [ ]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6) # 1 = 2, 2 = 3, 3 = 1