<a href="https://colab.research.google.com/github/LEESUNG02/colab_note/blob/main/230621_numpy_02_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
#@title 백터와 연산
x = np.arange(1, 10001)
y = np.arange(10001, 20001)
x, y

(array([    1,     2,     3, ...,  9998,  9999, 10000]),
 array([10001, 10002, 10003, ..., 19998, 19999, 20000]))

In [4]:
z = x + y
z

array([10002, 10004, 10006, ..., 29996, 29998, 30000])

In [5]:
x == y


array([False, False, False, ..., False, False, False])

In [8]:
(x == y) | (x < y)

array([ True,  True,  True, ...,  True,  True,  True])

In [9]:
a = np.arange(1, 5)
a

array([1, 2, 3, 4])

In [10]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [11]:
10 ** a

array([   10,   100,  1000, 10000])

In [12]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [15]:
#@title 스칼라/백터
x = np.arange(10)
x= x.ndim, x.shape

In [16]:
x * 100 # -> 100 -> x라는 배열의 모양에 맞춰서 변형

(1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,
 (10,),
 1,


In [18]:
x = np.arange(12).reshape(-1, 4)
x, x.ndim, x.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 2,
 (3, 4))

In [19]:
x * 100

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [22]:
#@title 브로드캐스팅
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [24]:
x + 1, x+2, x-3

(array([1, 2, 3, 4, 5]), array([2, 3, 4, 5, 6]), array([-3, -2, -1,  0,  1]))

In [26]:
x = np.arange(15).reshape(5, -1)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [27]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [29]:
# x+y -> 차원이 달라서 불가
y2 = y[:, np.newaxis]
y2, y2.shape  # -> 차원을 맞춰주면 가능


(array([[0],
        [1],
        [2],
        [3],
        [4]]),
 (5, 1))

In [30]:
x + y2 # y2 -> 짧았음 -> 1열 -> 3열 (반복확장)

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18]])

In [53]:
#@title 차원 축소 연산
x =  np.random.randint(0, 100, 6)
x

array([34, 46, 31, 95, 48, 56])

In [54]:
print(np.sum(x), x.sum())
print(np.max(x), x.max())  # 최대
print(np.min(x), x.min())  # 최소
print(np.argmax(x), x.argmax())  # 최대 -> 인덱스
print(np.argmin(x), x.argmin())  # 최소 -> 인덱스
print(np.mean(x), x.mean(), np.sum(x) / len(x))  # 평균
print(np.median(x))  # 중간값 -> 짝수개 -> 평균
print(np.all(x > 50), (x > 50).all())  # 모두 True인지
print(np.any(x > 50), (x > 50).any())  # 1개 이상 True인지

310 310
95 95
31 31
3 3
2 2
51.666666666666664 51.666666666666664 51.666666666666664
47.0
False False
True True


In [55]:
x = np.random.randint(0, 100, 6).reshape(2, -1)
x

array([[30, 88, 14],
       [ 4,  1, 78]])

In [56]:
print(x.sum(), x.sum(axis=None))
print(x.sum(axis=0))  # 같은 행을 합쳐주겠다 -> 열 모양
print(x.sum(axis=1))  # 같은 열을 합쳐주겠다 -> 행 모양

215 215
[34 89 92]
[132  83]


In [57]:
x

array([[30, 88, 14],
       [ 4,  1, 78]])

In [59]:
np.sort(x), np.sort(x, axis=-1), np.sort(x, axis=1) # ndim-1 차원

(array([[14, 30, 88],
        [ 1,  4, 78]]),
 array([[14, 30, 88],
        [ 1,  4, 78]]),
 array([[14, 30, 88],
        [ 1,  4, 78]]))

In [61]:
np.sort(x, axis=0), np.sort(x, axis=0)[:,::-1]

(array([[ 4,  1, 14],
        [30, 88, 78]]),
 array([[14,  1,  4],
        [78, 88, 30]]))

In [62]:
np.sort(x, axis=1), np.sort(x, axis=1)[::-1,:]

(array([[14, 30, 88],
        [ 1,  4, 78]]),
 array([[ 1,  4, 78],
        [14, 30, 88]]))

In [63]:
a.sort()
a

array([1, 2, 3, 4])

In [64]:
np.argsort(a)

array([0, 1, 2, 3])

In [72]:
#@title 기술 통계
x = np.random.randint(-100, 100, 30)
x

array([ -59,  -40,  -37,   33,  -92,   74,  -66,    4,   47,   -3,  -25,
         29,   81,   95,  -40,   48,   25,   92, -100,  -53,    9,  -31,
        -14,   43,   23,   12,    1,   53,   76,   28])

In [70]:
print(len(x))
print(np.mean(x), x.mean())
print(np. var(x), x.var())
print(np.std(x), |x.std())
print(np.max(x), x.max())
print(np.min(x), x.min())
print(np.median(x))
print(np.percentile(x, 0))
print(np.percentile(x, 25), np.percentile(x, 1 * 100 / 4))
print(np.percentile(x, 50), np.percentile(x, 2 * 100 / 4))
print(np.percentile(x, 75), np.percentile(x, 4 * 100 / 4))
print(np.percentile(x, 100), np.percentile(x, 4 * 100 / 4))

30
6.666666666666667 6.666666666666667
3243.3555555555554 3243.3555555555554
56.95046580630887 56.95046580630887
86 86
-97 -97
15.0
-97.0
-35.0 -35.0
15.0 15.0
56.75 86.0
86.0 86.0


In [73]:
#@title 난수 발생
np.random.seed(2023)

In [74]:
np.random.rand(5)

array([0.3219883 , 0.89042245, 0.58805226, 0.12659609, 0.14134122])

In [100]:
# np.random.rand((2,5))  # shape 직접 지정 안됨

In [76]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
np.random.shuffle(x)
x

array([7, 4, 3, 2, 8, 9, 1, 6, 0, 5])

In [80]:
print(np.random.choice(5, 5, replace=False))
print(np.random.choice(5, 3, replace=False))

[3 4 0 2 1]
[3 4 2]


In [81]:
print(np.random.choice(5, 3, replace=True))
print(np.random.choice(5, 10))

[0 1 0]
[1 2 3 1 0 1 4 0 0 4]


In [82]:
np.random.rand(10)

array([0.26546361, 0.20533187, 0.40615836, 0.62311131, 0.80221535,
       0.09702613, 0.81625998, 0.02808046, 0.01545164, 0.56690572])

In [83]:
np.random.randn(10) # rand, randn -> shape (배열의 모양) (2, 3)

array([ 0.78604475,  0.17643234, -0.16326137, -0.09505149, -1.06584426,
       -0.91283631, -0.66864652,  1.55496137, -1.47845086, -0.11497552])

In [84]:
# 기대값 3, 표준편차 0.5
np.random.randn(10) * 0.5 + 3

array([3.88938001, 3.59074486, 3.38436627, 2.42663623, 3.70916688,
       2.55121923, 3.50435384, 2.61183864, 3.42062693, 3.5254669 ])

In [87]:
np.random.randint(1, 10, 100)

array([6, 3, 6, 2, 3, 9, 7, 8, 7, 5, 9, 5, 4, 5, 8, 9, 8, 5, 5, 9, 7, 1,
       9, 8, 2, 9, 2, 9, 1, 7, 7, 6, 6, 5, 4, 5, 7, 6, 5, 4, 2, 3, 4, 6,
       8, 6, 3, 5, 1, 7, 4, 8, 6, 7, 4, 4, 1, 4, 5, 5, 6, 8, 4, 9, 2, 4,
       9, 2, 4, 4, 4, 2, 8, 8, 2, 5, 9, 3, 5, 2, 4, 8, 8, 3, 3, 9, 7, 8,
       7, 5, 6, 9, 4, 6, 8, 1, 1, 7, 6, 1])

In [89]:
r = np.random.randint(1, 10, 100)
r

array([9, 9, 1, 9, 8, 7, 2, 9, 9, 5, 3, 9, 4, 9, 2, 3, 9, 1, 4, 6, 3, 4,
       8, 2, 9, 8, 8, 4, 9, 9, 3, 1, 5, 2, 7, 3, 9, 7, 5, 8, 3, 8, 6, 9,
       2, 2, 7, 3, 9, 7, 8, 6, 2, 6, 6, 8, 2, 6, 7, 6, 5, 9, 4, 6, 8, 2,
       9, 9, 4, 5, 1, 2, 5, 7, 6, 8, 9, 2, 8, 4, 3, 3, 9, 3, 5, 3, 3, 3,
       9, 1, 4, 8, 1, 7, 8, 7, 8, 9, 2, 4])

In [91]:
np.unique(r)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
np.unique(r, return_counts=True) # 1:고유값 2: 고유값마다 몇 개가 있는지

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 6, 12, 13,  9,  7,  9,  9, 14, 21]))

In [95]:
index, value = np.unique(r, return_counts=True)
index, value

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 6, 12, 13,  9,  7,  9,  9, 14, 21]))

In [96]:
zip(index, value)

In [97]:
dict(zip(index, value))

{1: 6, 2: 12, 3: 13, 4: 9, 5: 7, 6: 9, 7: 9, 8: 14, 9: 21}