<a href="https://colab.research.google.com/github/LEESUNG02/colab_note/blob/main/ch05_01_numpy_%EA%B8%B0%EC%B4%88_%EA%B3%B5%EC%9C%A0%EC%9A%A9_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 기초

## 배열(Array)
* 많은 데이터를 하나의 변수에 넣는 법? : **리스트**
* 하지만 리스트는...
    * 속도가 느리다
    * 메모리를 많이 차지한다

> 그래서? **배열(Array)**을 사용한다

* 적은 메모리로 많은 데이터를 빠르게 처리할 수 있음

## 특징
1. 모든 원소가 같은 **자료형**이어야 함
2. 원소의 갯수를 바꿀 수 없음

> 그런데 파이썬은 자체적으로 배열 자료형을 제공하지 않음<br>
> 그래서 우리는 **넘파이(Numpy)** 패키지를 import해서 사용

In [ ]:
1   # 파이썬 pip -> 외부 패키지 관리자 (틀들, 기능들 -> 패키지 -> 불러오기)
2   # 파이썬은 numpy가 내장이 아니기 떄문에... -> pip install numpy
3   # 1. anaconda -> numpy가 딸려들어옴
4   # 2. colab -> nimpy가 이미 설치
5   import nimpy # import 가져오기 -> 이미 설치된 numpy라는 기능을 구축한다
6   # 너무 자주 쓰이기 떄문에 nupy라는 전체 이름을 쓰지 않고 전체 이름을 쓰지 않고 np라는 축약어를 사용
7   import numpy as np # 다른 이름을 주지 마세요
8   # tap 입력시 자동입력
9   import unmpy as np
10  # https://www.kaggle.com/
11  # https://dacon.io/
12  # https://datascienceschool.net/intro.html
13  # https://www.youtube.com/c/todaycode

## 1차원 배열
* 리스트나 튜플처럼 한 줄로 이루어진 형태의 배열

In [ ]:
I np.array([1, 2, 3]) # 마지막에 실행된 실행문의 결과를 아래 블록에 표시 (변수명, 값, 함수들...)

SyntaxError: ignored

array([1, 2, 3])

In [ ]:
1 arr = np.array(range(10))

SyntaxError: ignored

## ndarray
* 배열 객체 타입(자료형)
* 리스트와 동일해 보이지만 차이가 많음

|자료형|특징|
|:-|:-|
|리스트(list)|각각의 원소가 다른 자료형이 될 수 있음|
|배열(array)|연속적인 메모리 배치를 가지기 때문에 모든 원소가 같은 자료형이어야 함<br>원소에 대한 접근과 반복문 실행이 빨라짐|

In [ ]:
 1 import random
 2
 3 def average_python(n): # n개의 길이
 4     '''
 5     n개의 랜덤한 D-1 사이의 실수를 평균해주는 함수
 6     '''
 7     s = 0 # 총 합계
 8     for i in range(n):
 9         s += random() # 총함
10    return s / n # 총합 / 갯수 => 산술 평균
11
12 # ctrl = enter => 한 개의 블록 실행 혹은 왼쪽 play button

SyntaxError: ignored

CPU times: user 11.7 ms, sys: 0 ns, total: 11.7 ms
Wall time: 12.3 ms


0.49918047222864326

6.48 ms ± 220 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


CPU times: user 1.54 ms, sys: 28 µs, total: 1.57 ms
Wall time: 1.19 ms


0.5002374035185094

548 µs ± 6.69 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## 벡터화 연산
* 배열 객체는 **배열의 각 원소에 대한 반복 연산을 하나의 명령어로 처리**하는 벡터화 연산(vectorized operation)을 지원

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# 여러 개의 데이터를 모두 2배 할 때 (파이썬)


CPU times: user 11 µs, sys: 1 µs, total: 12 µs
Wall time: 13.8 µs


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [ ]:
# 리스트 컴프리헨션


CPU times: user 19 µs, sys: 1e+03 ns, total: 20 µs
Wall time: 22.4 µs


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [ ]:
# 벡터화 연산


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# 리스트 객체에 정수를 곱하면 객체의 크기가 해당 정수 배만큼 증가


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

* 벡터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용

(array([1, 2, 3]), array([10, 20, 30]))

array([12, 24, 36])

(array([False,  True, False]), array([False,  True,  True]))

(array([False,  True, False]), array([False,  True,  True]))

## 2차원 배열
* `ndarray`는 N-dimensional Array의 약자, 즉 1차원 배열 이외에도 2차원 배열, 3차원 배열 등의 다차원 배열 자료 구조를 지원
* 2차원 배열 = 행렬 (matrix)
* 가로줄 : 행(row), 세로줄 : 열(column)
> 엑셀 스프레드시트와 같은 형태의 배열

* 리스트의 리스트(list of list)를 이용하여 2차원 배열 생성
    * 안쪽 리스트의 길이 : 행렬의 열의 수 (가로 크기)
    * 바깥쪽 리스트의 길이 : 행렬의 행의 수 (세로 크기)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# 행의 갯수, 열의 갯수


(2, 3)

## 💡 연습문제 1
> 아래 모양의 행렬 만들어 보기
```
10 20 30 40
50 60 70 80
```

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 3차원 배열

In [ ]:
# 크기를 나타낼 때는 가장 바깥쪽 리스트의 길이부터 가장 안쪽 리스트 길이의 순서로 표시


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [ ]:
# 깊이, 행, 열


(2, 3, 4)

## 배열의 차원과 크기 알아내기
* `ndim`, `shape` **속성** 사용
> 속성 : 괄호 없이 이름만 써서 값을 호출

* `ndim` : 배열의 차원
* `shape` : 배열의 크기

(1, (3,))

(2, (2, 3))

(3, (2, 3, 4))

## 배열의 복사
* copy와 view의 차이점은 copy는 새 배열(깊은 복사)이고 view는 원래 배열과 연결 되어 있다는 것(얕은 복사)
* copy는 데이터를 소유하며 copy에 대한 변경 사항은 원본 배열에 영향을 미치지 않으며 원본 배열에 대한 변경은 copy에 영향을 주지 않음
* view는 데이터를 소유하지 않으며 view에 대한 모든 변경 사항은 원래 배열에 영향을 미치고 원래 배열에 대한 모든 변경 사항은 보기에 영향을 줌

[42  2  3  4  5]
[1 2 3 4 5]


[42  2  3  4  5]
[42  2  3  4  5]


None
[1 2 3 4 5]


## 배열의 인덱싱

### 일차원 배열
* 리스트의 인덱싱과 같음

(2, 4)

### 다차원 배열
* 콤마(comma, `,`)를 사용하여 접근
* 콤마로 구분된 차원을 축(axis)라고 함
    * like 그래프의 x축, y축

array([[0, 1, 2],
       [3, 4, 5]])

0

1

5

## 배열 슬라이싱
* 다차원 배열의 원소 중 2개 이상의 복수 개를 접근하려면 일반적인 파이썬 슬라이싱(slicing)과 comma(,)를 함께 사용

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

array([0, 1, 2, 3])

array([1, 5])

array([5, 6, 7])

array([[0, 1],
       [4, 5]])

## 💡 연습문제 2

In [ ]:
m = np.array([[0,  1,  2,  3,  4],
              [5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
#@markdown (1) 값 7을 인덱싱


(7, 7, 7, 7)

In [ ]:
#@markdown (2) 값 14을 인덱싱


(14, 14, 14, 14)

In [ ]:
#@markdown (3) 배열 [6,7]을 슬라이싱


(array([6, 7]), array([6, 7]), array([6, 7]), array([6, 7]))

In [ ]:
#@markdown (4) 배열 [7,12]을 슬라이싱


(array([ 7, 12]), array([ 7, 12]), array([ 7, 12]), array([ 7, 12]))

In [ ]:
#@markdown (5) 배열 [[3,4],[8,9]]을 슬라이싱


[[3 4]
 [8 9]]
[[3 4]
 [8 9]]
[[3 4]
 [8 9]]
[[3 4]
 [8 9]]


## 배열 인덱싱
* 대괄호(Bracket, [])안의 인덱스 정보로 숫자나 슬라이스가 아니라 위치 정보를 나타내는 또다른 `ndarray` 배열을 받을 수 있음 (인덱스 배열)
* 일종의 조건 검색 기능

### 불리언 (Boolean) 배열 인덱싱
* 인덱스 배열의 원소가 True, False 두 값으로만 구성되며 인덱스 배열의 크기가 원래 ndarray 객체의 크기와 같아야 함

In [ ]:
# 짝수인 원소만 골라내고 싶다면?
# 짝수에 대응하는 곳에 True, 홀수에 대응하는 곳에 False


array([0, 2, 4, 6, 8])

In [ ]:
# 조건문 연산


array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

array([0, 2, 4, 6, 8])

### 정수 배열 인덱싱
* 인덱스 배열의 원소 각각이 원래 `ndarray` 객체 원소 하나를 가리키는 인덱스 정수이여야 함

array([11, 33, 55, 77, 99])

* 이 때는 배열 인덱스의 크기가 원래의 배열 크기와 달라도 상관없음
* 같은 원소를 반복해서 가리키는 경우에는 배열 인덱스가 원래의 배열보다 더 커지기도 함

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

### 다차원 배열에서의 배열 인덱싱

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

## 💡 연습문제 3

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
# (1) 3의 배수 찾기


array([ 3,  6,  9, 12, 15, 18])

In [ ]:
# (2) 4로 나누면 1이 남는 수 찾기


array([ 1,  5,  9, 13, 17])

In [ ]:
# (3) 3로 나누면 나누어지고 4로 나누면 1이 남는 수 찾기


array([9])

## 배열 검색

(array([3, 5, 6]),)

(array([1, 3, 5, 7]),)